UdruzenjeApp/Models/Grad.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace UdruzenjeApp.Models
{
    public class Grad
    {
        [Key]
        public int ID { get; set; }
        public string Naziv { get; set; }
        
        [ForeignKey("Drzava")]
        public int DrzavaID { get; set; }
        public Drzava drzava { get; set; }
    }
}

UdruzenjeApp/Controllers/GradController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UdruzenjeApp.Data;
using UdruzenjeApp.Models;
using UdruzenjeApp.ViewModels;

namespace RSI_Seminarski_V1.Controllers
{
   
    public class GradController : Controller
    {
            ApplicationDbContext db = new ApplicationDbContext();

        public IActionResult Prikazi()
        {
            List<GradDodajVM> model = db.grad
                .Select(k => new GradDodajVM
                {
                    Naziv = k.Naziv,
                    GradID = k.ID
                }).ToList();
            ViewData["podaci"] = model;

            return View(model);
        }
        public IActionResult Delete(int TrazeniID)
        {
           
            Grad temp = db.grad.Where(k => k.ID == TrazeniID).SingleOrDefault();
            if (temp == null)
                return View("Error");
            db.Remove(temp);
            db.SaveChanges();
            return RedirectToAction(nameof(Prikazi));
        }

        public IActionResult Dodaj()
        {
            
            GradDodajVM model = new GradDodajVM();
            model.DrzavaStavke = db.drzava.Select(j => new SelectListItem(j.Naziv, j.ID.ToString())).ToList();
            return PartialView("uredi", model);
        }

        public IActionResult Uredi(int GRADID)
        {
           
            Grad c = db.grad.SingleOrDefault(b => b.ID == GRADID);
            if(c==null)
            {
                TempData["porukaError"] = "Greska prilikom uredjivanja Grada";
                return View("Error");
            }
            GradDodajVM model = new GradDodajVM();
            model.GradID = c.ID;
            model.DrzavaStavke = db.drzava.Select(j => new SelectListItem(j.Naziv, j.ID.ToString())).ToList();
            model.Naziv = c.Naziv;
            model.DrzavaID = c.DrzavaID;

            return PartialView("uredi", model);
        }

        public IActionResult Snimi(GradDodajVM model)
        {
            
            Grad c;
            if (model.GradID == 0)
            {
                c = new Grad();
                db.Add(c);
                TempData["porukaSucces"] = "Uspjesno ste dodali Grad";
            }
            else
            {
                c = db.grad.FirstOrDefault(x => x.ID == model.GradID);
                TempData["porukaSucces"] = "Uspjesno ste dodali Grad";
            }
            c.ID = model.GradID;
            c.Naziv = model.Naziv;
            c.DrzavaID = model.DrzavaID;

            db.SaveChanges();
            db.Dispose();

            return RedirectToAction(nameof(Prikazi));
        }
    }
}

UdruzenjeApp/Views/Grad/Prikazi.cshtml
@using UdruzenjeApp.ViewModels
@model List<UdruzenjeApp.ViewModels.GradDodajVM>

@{
    
    int b = 0;
}

<div id="prikaz" class=" container">
    <h2>Prikazi</h2>

    <table class="table table-hover table-bordered ">
        <thead>
            <tr>
                <th>RB</th>
                <th>Naziv grada</th>
            </tr>
        </thead>
        <tbody>
            @foreach (GradDodajVM x in Model)
            {
                <tr>
                    @{
                        b++;
                    }
                    <td>@b</td>
                    <td>@x.Naziv</td>

                    <td>
                        <a href="/Grad/Delete?TrazeniID=@x.GradID" class="btn btn-danger">  Obrisi </a>
                        <a href="/Grad/Uredi?GradID=@x.GradID" class="btn btn-warning" ajax-url="/Grad/Uredi?GradID=@x.GradID" ajax-rezultat="nekiID" ajax-poziv="da">  Uredi </a>
                    </td>

                </tr>
            }
        </tbody>
        </table>
    <button id="idButton" class="btn btn-success" ajax-rezultat="nekiID" ajax-poziv="da" ajax-url="/Grad/Dodaj/">Dodaj</button>
    <div id="nekiID">


    </div>
</div>

UdruzenjeApp/Views/Grad/Uredi.cshtml
@model UdruzenjeApp.ViewModels.GradDodajVM


@{
    ViewData["Title"] = "uredi";
}

<h2>Edit Grada</h2>
<hr />

<div class="row">
    <div>
        <form asp-action="Snimi" asp-controller="Grad">

            <input type="hidden" value="@Model.GradID" name="GradID" class="form-control" />


            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DrzavaID" class="control-label"></label>
                <select asp-for="DrzavaID" asp-items="Model.DrzavaStavke" class="form-control"></select>
            </div>


            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>