UdruzenjeApp/Models/Dogadjaj.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace UdruzenjeApp.Models
{
    public class Dogadjaj
    {
        [Key]
        public int ID { get; set; }
        public string Naziv { get; set; }
        public DateTime VrijemeOdrzavanja { get; set; }
        public string opis { get; set; }
        public bool OgranicenoMjesta { get; set; }
        public int brojMjesta { get; set; }

        public int UpraviteljID { get; set; }
        [ForeignKey("UpraviteljID")]
        public ApplicationUser Upravitelj { get; set; }

        [ForeignKey("Grad")]
        public int GradID { get; set; }
        public Grad grad { get; set; }

    }
}

UdruzenjeApp/Controllers/DogadjajController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UdruzenjeApp.Data;
using UdruzenjeApp.Models;
using UdruzenjeApp.ViewModels;

namespace UdruzenjeApp.Controllers
{
    [Authorize (Roles ="Admin")]
    public class DogadjajController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private readonly UserManager<ApplicationUser> _userManager;

        public DogadjajController(UserManager<ApplicationUser>userManager)
        {
            _userManager = userManager;       
        }

        public IActionResult Prikazi(string NazivDogadjaja, int? GradId)
        {
            DogadjajiViewModel model =new  DogadjajiViewModel();
                model.rows = db.dogadjaj
                .Where(y=>(y.GradID==GradId || GradId==null)&&(y.Naziv.Contains(NazivDogadjaja)||NazivDogadjaja==null))
                .Select(d => new DogadjajiViewModel.Row
                {
                    Naziv = d.Naziv,
                    opis = d.opis,
                    OgranicenoMjesta = d.OgranicenoMjesta,
                    brojMjesta = d.brojMjesta,
                    VrijemeOdrzavanja = d.VrijemeOdrzavanja,
                    DogadjajID = d.ID,
                    grad = db.grad.FirstOrDefault(x => x.ID == d.GradID).Naziv,
                   

                }).ToList();
            model.gradovi =new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Value=string.Empty,
                    Text="(Odaberite Grad)"
                }
            };
            model.gradovi.AddRange(db.grad.Select(g => new SelectListItem(g.Naziv, g.ID.ToString()))); 
            
            ViewData["podaci"] = model;

            return View(model);
        }

        public IActionResult Delete(int TrazeniID)
        {
            Dogadjaj temp = db.dogadjaj.Where(d => d.ID == TrazeniID).SingleOrDefault();
            if (temp == null)
                return View("Error");
            db.Remove(temp);
            db.SaveChanges();

            return Redirect("/Dogadjaj/Prikazi");
        }
        public IActionResult Dodaj()
        {
           
            DogadjajDodajVM model = new DogadjajDodajVM();
            int idc = int.Parse(_userManager.GetUserId(principal: HttpContext.User));
            model.ImeClana = db.Users.FirstOrDefault(x => x.Id == idc).Ime;
            model.UpraviteljID = idc;
            // model.upraviteljStavke = db.Users.Select(u =>new SelectListItem( u.Ime + " " + u.Prezime,u.Id.ToString())).ToList();
            model.gradStavke = db.grad.Select(g => new SelectListItem(g.Naziv, g.ID.ToString())).ToList();
            return PartialView("uredi",model);
        }
        public IActionResult Uredi(int DogadjajID)
        {
            Dogadjaj d = db.dogadjaj.SingleOrDefault(b => b.ID == DogadjajID);
            if(d==null)
            {
                TempData["porukaError"] = "Greskaa prilikom uredjivanja Dogadjaja";
                return View("Error");
            }
            DogadjajDodajVM model = new DogadjajDodajVM();
            int idc = int.Parse(_userManager.GetUserId(principal: HttpContext.User));
            model.ImeClana = db.Users.FirstOrDefault(x => x.Id == idc).Ime;
            model.DogadjadajID = d.ID;
            model.gradStavke = db.grad.Select(g => new SelectListItem(g.Naziv, g.ID.ToString())).ToList();
            model.opis = d.opis;
            model.Naziv = d.Naziv;
            model.OgranicenoMjesta = d.OgranicenoMjesta;
            model.VrijemeOdrzavanja = d.VrijemeOdrzavanja;
            model.brojMjesta = d.brojMjesta;
            model.GradID = d.GradID;
            model.UpraviteljID = idc;

            return PartialView("uredi", model);
        }
        public IActionResult Snimi(DogadjajDodajVM model)
        {
            Dogadjaj d;
            if(model.DogadjadajID == 0)
            {
                d = new Dogadjaj();
                db.Add(d);
                TempData["porukaSuccss"] = "Uspjesno ste Dodalli dogadjaj";
            }
            else
            {
                d = db.dogadjaj.FirstOrDefault(x => x.ID == model.DogadjadajID);
                TempData["porukaSuccss"] = "Uspjesno ste Izmjenili dogadjaj";

            }
            d.ID = model.DogadjadajID;
            d.opis = model.opis;
            d.Naziv = model.Naziv;
            d.OgranicenoMjesta = model.OgranicenoMjesta;
            d.VrijemeOdrzavanja = model.VrijemeOdrzavanja;
            d.brojMjesta = model.brojMjesta;
            d.UpraviteljID = model.UpraviteljID;
            d.GradID = model.GradID;

            
            db.SaveChanges();
            db.Dispose();
            return RedirectToAction(nameof(Prikazi));
        }
        public int getBrojDogadjaja() { return db.dogadjaj.ToList().Count(); }
    }
    
}

UdruzenjeApp/Views/Dogadjaj/Prikazi.cshtml
@using UdruzenjeApp.ViewModels

@model DogadjajiViewModel
@{
    //ViewData["Title"] = "Prikazi";
    //var rezultat = (List<DogadjajiViewModel>)ViewData["podaci"];
    int b = 0;
}
<style>
    body {
        padding-left: 1%;
        padding-right: 1%;
    }
</style>

<script src="~/js/ajaxScript.js"></script>
<br />

<div id="prikaz" class=" ">
    <h2>Prikaz Dogadjaja</h2>
    <br />
    <form class="form-inline" asp-action="Prikazi" asp-controller="Dogadjaj" asp-route-NazivDogadjaja="@Model.NazivDogadjaja" asp-route-GradId="@Model.GradId">
            <p>
                Naziv: <input asp-for="NazivDogadjaja" class="form-control mr-3" type="text" >
                <input class="btn btn-dark" type="submit" value="Filter" />
            </p>
            <p style="margin-left:3%;">
                Grad: <select asp-for="GradId" asp-items="@Model.gradovi" class="form-control mr-3"></select>
                <input class="btn btn-dark" type="submit" value="Filter" />
            </p>
        </form>
    <table class="table table-hover table-bordered ">
        <thead>
            <tr>
                <th>RB</th>
                <th>Naziv</th>
                <th>Vrijeme</th>
                <th>Opis</th>
                <th>Mjesto</th>
                <th>Akcija</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var k in Model.rows) { }
            @foreach (var x in Model.rows)
            {
                <tr>
                    @{
                        b++;
                    }
                    <td>@b</td>
                    <td>@x.Naziv</td>
                    <td>@x.VrijemeOdrzavanja</td>
                    <td>@x.opis</td>
                    <td>@x.grad</td>


                    <td>
                        <a href="/Dogadjaj/Delete?TrazeniID=@x.DogadjajID" class="btn btn-danger">  Obrisi </a>

                        <a href="/Dogadjaj/Uredi?DogadjajID=@x.DogadjajID" class="btn btn-warning" ajax-url="/Dogadjaj/Uredi?DogadjajID=@x.DogadjajID" ajax-rezultat="nekiID" ajax-poziv="da">  Uredi </a>

                    </td>

                </tr>
            }
        </tbody>
    </table>
    <button id="idButton" class="btn btn-primary btn-lg" ajax-rezultat="nekiID" ajax-poziv="da" ajax-url="/Dogadjaj/Dodaj/">Dodaj</button>
    <div id="nekiID">


    </div>
</div>

UdruzenjeApp/Views/Dogadjaj/uredi.cshtml
@model UdruzenjeApp.ViewModels.DogadjajDodajVM

@{
   ViewData["Title"] = "uredi";
}

@*<div class="alert-primary" role="alert" id="porukaBox">
  This is a primary alert—check it out!
</div>*@
<style>
    body {
        padding-left: 1%;
        padding-right: 1%;
    }
</style>
<br />
<h2 style="margin-left:25px">Edit Dogadjaja</h2>
<hr />

<div class="container " style="margin-left:25px; background-color:beige;">
    <div >
        <form asp-action="Snimi" asp-controller="Dogadjaj" class="form-group">

            <input type="hidden" value="@Model.DogadjadajID" name="DogadjadajID" class="form-control" />
            <input asp-for="UpraviteljID" hidden />

            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VrijemeOdrzavanja" class="control-label"></label>
                <input asp-for="VrijemeOdrzavanja" class="form-control" />
                <span asp-validation-for="VrijemeOdrzavanja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="opis" class="control-label"></label>
                @*<input asp-for="opis" class="form-control" />*@
                <textarea asp-for="opis" class="form-control"></textarea>
                <span asp-validation-for="opis" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="ImeClana" class="control-label"></label>
                <input asp-for="ImeClana"class="form-control" value="@Model.ImeClana" readonly />
            </div>
            <div class="form-group">
                <label asp-for="GradID" class="control-label">Grad</label>
                <select asp-for="GradID" asp-items="Model.gradStavke" class="form-control"></select>

            </div>


            <div class="form-group " style="margin-bottom:50px;;">
                <input type="submit" value="Snimi" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>