UdruzenjeApp/Models/Drzava.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UdruzenjeApp.Models
{
    public class Drzava
    {
        public int ID { get; set; }
        public string Naziv { get; set; }

    }
}

UdruzenjeApp/Controllers/DrzavaController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using UdruzenjeApp.Data;
using UdruzenjeApp.Models;
using UdruzenjeApp.ViewModels;

namespace UdruzenjeApp.Controllers
{
    public class DrzavaController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public IActionResult Prikazi()
        {
            
            List<DrzavaDodajVM> model = db.drzava
                .Select(k => new DrzavaDodajVM
                {
                    Naziv = k.Naziv,
                    DrzavaID = k.ID
                }).ToList();
            ViewData["podaci"] = model;

            return View(model);
        }
        public IActionResult Delete(int TrazeniID)
        {
            
            Drzava temp = db.drzava.Where(k => k.ID == TrazeniID).SingleOrDefault();
            if (temp == null)
                return View("Error");
            db.Remove(temp);
            db.SaveChanges();
            return RedirectToAction(nameof(Prikazi));
        }

        public IActionResult Dodaj()
        {
            
            DrzavaDodajVM model = new DrzavaDodajVM();
            return PartialView("uredi", model);
        }

        public IActionResult Uredi(int DRZAVAID)
        {
            
            Drzava c = db.drzava.SingleOrDefault(b => b.ID == DRZAVAID);
            if(c==null)
            {
                TempData["porukaError"] = "Greska prilikom uredjivanja Drzave";
                return View("Error");
            }
            DrzavaDodajVM model = new DrzavaDodajVM();
            model.DrzavaID = c.ID;
            model.Naziv = c.Naziv; 

            return PartialView("uredi", model);
        }

        public IActionResult Snimi(DrzavaDodajVM model)
        {
          
            Drzava c;
            if (model.DrzavaID == 0)
            {
                c = new Drzava();
                db.Add(c);
                TempData["porukaSucces"] = "Uspjesno ste dodali Drzavu";
            }
            else
            {
                c = db.drzava.FirstOrDefault(x => x.ID == model.DrzavaID);
                TempData["porukaSucces"] = "Uspjesno ste dodali Drzavu";
            }
            c.ID = model.DrzavaID;
            c.Naziv = model.Naziv;

            db.SaveChanges();
            db.Dispose();

            return RedirectToAction(nameof(Prikazi));
        }
    }
}

UdruzenjeApp/Views/Drzava/Prikazi.cshtml
@using UdruzenjeApp.ViewModels
@model List<UdruzenjeApp.ViewModels.DrzavaDodajVM>
@{
   
    int b = 0;
}

<div id="prikaz" class=" container">
    <h2>Prikazi</h2>

    <table class="table table-hover table-bordered ">
        <thead>
            <tr>
                <th>RB</th>
                <th>Naziv</th>
            </tr>
        </thead>
        <tbody>
            @foreach (DrzavaDodajVM x in Model)
            {
                <tr>
                    @{
                        b++;
                    }
                    <td>@b</td>
                    <td>@x.Naziv</td>


                    <td>
                        <a href="/Drzava/Delete?TrazeniID=@x.DrzavaID" class="btn btn-danger">  Obrisi </a>
                        <a href="/Drzava/Uredi?DrzavaID=@x.DrzavaID" class="btn btn-warning" ajax-url="/Clan/Uredi?ClanID=@x.DrzavaID" ajax-rezultat="nekiID" ajax-poziv="da">  Uredi </a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <button id="idButton" class="btn btn-success" ajax-rezultat="nekiID" ajax-poziv="da" ajax-url="/Drzava/Dodaj/">Dodaj</button>
    <div id="nekiID">


    </div>
</div>

UdruzenjeApp/Views/Drzava/Uredi.cshtml
@using UdruzenjeApp.ViewModels
@model UdruzenjeApp.ViewModels.DrzavaDodajVM


@{
    ViewData["Title"] = "uredi";
}

<h2>Edit Drzave</h2>
<hr />

<div class="row">
    <div>
        <form asp-action="Snimi" asp-controller="Drzava">

            <input type="hidden" value="@Model.DrzavaID" name="DrzavaID" class="form-control" />


            <div class="form-group ">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Snimi" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>